name: CI

on:
  push:
    branches: [ main ]
    tags: [ '*' ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Get the reference
      id: get_version
      run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2.0.0
      with:
        image: tonistiigi/binfmt:qemu-v6.1.0
        platforms: "linux/amd64,linux/arm64,linux/ppc64le,linux/s390x"

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
#    - name: Login to registry
#      uses: docker/login-action@v1
#      with:
#        registry: quay.io
#        username: ${{ secrets.DOCKER_USERNAME }}
#        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push
      uses: docker/build-push-action@v3.0.0
      with:
        platforms: "linux/amd64,linux/arm64,linux/ppc64le,linux/s390x"
        push: false
        tags: ${{ steps.get_version.outputs.VERSION }}