name: CI

on:
  push:
    branches: [ main ]
    tags: [ '*' ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Get the reference
      id: get_version
      run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to registry
      uses: docker/login-action@v1
      with:
        registry: quay.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build
      run: |
        docker build -t quay.io/leonardo_cecchi/webtest:${{ steps.get_version.outputs.VERSION }} .
    - name: Push
      run: docker push quay.io/leonardo_cecchi/webtest:${{ steps.get_version.outputs.VERSION }}
