name: CI

on:
  push:
    branches: [ main ]
    tags: [ '*' ]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source code
      uses: actions/checkout@v3.0.2

    - name: Get the reference
      id: get_version
      run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)

    - name: Image metadata
      id: metadata
      uses: docker/metadata-action@v4
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2.0.0
      with:
        image: tonistiigi/binfmt:qemu-v6.2.0
        platforms: "linux/amd64,linux/arm64,linux/arm/v7,linux/ppc64le,linux/s390x"

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2.0.0

    - name: Login to registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v3.1.0
      with:
        context: .
        platforms: "linux/amd64,linux/arm64,linux/arm/v7,linux/ppc64le,linux/s390x"
        tags: ${{ steps.metadata.outputs.tags }}
        push: true
